about/urls.py
from django.urls import path

from about import views

app_name = "about"
urlpatterns = [
    path("", views.Landing.as_view(), name="landing"),
]

contact/urls.py
from django.urls import path

from contact import views

app_name = "contact"
urlpatterns = [
    path("contact-entry/create/", views.ContactEntryCreate.as_view(), name="contact_entry_create"),
    path("contact-entry/success/", views.ContactEntrySuccess.as_view(), name="contact_entry_success"),
]

home/urls.py
from django.urls import path

from home import views

app_name = "home"
urlpatterns = [
    path("", views.Landing.as_view(), name="landing")
]

it_assist/urls.py
from django.urls import path

from it_assist import views

app_name = "it_assist"
urlpatterns = [
    path("", views.Landing.as_view(), name="landing"),
]

trevor_watson/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls


urlpatterns = [
    path('about/', include('about.urls')),
    path('contact/', include('contact.urls')),
    path('', include('home.urls')),
    path('it/', include('it_assist.urls')),
    path('admin/', admin.site.urls),

    # wagtail
    path('cms/', include(wagtailadmin_urls)),
    path('documents/', include(wagtaildocs_urls)),
    path('blog/', include(wagtail_urls)),
]


if settings.DEBUG:
    # django-debug-toolbar
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

about/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db import models

from modelcluster.fields import ParentalKey
from modelcluster.contrib.taggit import ClusterTaggableManager
from taggit.models import TaggedItemBase, Tag as TaggitTag
from wagtailcodeblock.blocks import CodeBlock

from wagtail.core import blocks
from wagtail.core.fields import StreamField
from wagtail.core.models import Page
from wagtail.admin.edit_handlers import (
    FieldPanel, StreamFieldPanel, MultiFieldPanel
)
from wagtail.images.blocks import ImageChooserBlock
from wagtail.search import index


class Index(Page):

    sub_title = models.CharField(max_length=120, null=True, blank=True)
    description = models.CharField(max_length=255, null=True, blank=True)

    content_panels = Page.content_panels + [
        FieldPanel("sub_title"),
        FieldPanel("description", classname="full"),
    ]

    def get_context(self, request, *args, **kwargs):
        """
            Adding custom stuff to our context.
            https://learnwagtail.com/tutorials/how-to-paginate-your-wagtail-pages/
        """
        context = super().get_context(request, *args, **kwargs)

        # Get all posts
        all_posts = self.get_posts(request.GET.get("tag"))

        # Paginate all posts by 5 per page
        paginator = Paginator(all_posts, 5)

        # Try to get the ?page=x value
        page = request.GET.get("page")
        try:
            # If the page exists and the ?page=x is an int
            posts = paginator.page(page)
        except PageNotAnInteger:
            # If the ?page=x is not an int; show the first page
            posts = paginator.page(1)
        except EmptyPage:
            # If the ?page=x is out of range (too high most likely)
            # Then return the last page
            posts = paginator.page(paginator.num_pages)

        # "posts" will have child pages; you'll need to use .specific in the template
        # in order to access child properties, such as youtube_video_id and subtitle
        context["posts"] = posts

        tags = TaggitTag.objects.filter(post__isnull=False)
        tags = tags.distinct()
        tags = tags.order_by("name")
        context["tags"] = tags
        return context

    def get_posts(self, tag=None):
        posts = Post.objects.live().public()
        if tag:
            posts = posts.filter(tags__name=tag)
        posts = posts.order_by("-first_published_at")
        return posts


class Post(Page):

    date = models.DateField("Post Date")
    intro = models.CharField(max_length=255)
    body = StreamField([
        ("heading", blocks.CharBlock(classname="full title")),
        ("paragraph", blocks.RichTextBlock(
            features=[
                "h1", "h2", "h3", "h4", "h5", "h6", "bold", "italic", "ol",
                "ul", "hr", "link", "documen", "image", "embed", "code",
                "blockquote",
            ])
        ),
        ("image", ImageChooserBlock(classname="img-fluid")),
        ("code", CodeBlock()),
    ])
    tags = ClusterTaggableManager(through="Tag", blank=True)

    search_fields = Page.search_fields + [
        index.SearchField("intro"),
        index.SearchField("body"),
    ]

    content_panels = Page.content_panels + [
        MultiFieldPanel([FieldPanel("date"), FieldPanel("tags")]),
        FieldPanel("intro", classname="full"),
        StreamFieldPanel("body"),
    ]

    def get_tags(self):
        return TaggitTag.objects.filter(post=self).order_by("name")


class Tag(TaggedItemBase):

    content_object = ParentalKey(
        "Post", related_name="tagged_items", on_delete=models.CASCADE
    )

contact/models.py
from django.conf import settings
from django.core.mail import mail_managers
from django.db import models
from django.template.loader import get_template


class ContactEntry(models.Model):

    created = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=120)
    email = models.EmailField()
    message = models.TextField()
    sent = models.BooleanField(default=False)

    def __str__(self):
        return f"Contact Entry from {self.name}"

    @classmethod
    def send_entries(cls):
        """
            Email all new entries to EMAIL_HOST_USER
        """
        entries = cls.objects.filter(sent=False)
        if entries:
            template = get_template("contact/email.txt")
            mail_managers(
                subject="New Contact Entry",
                message=template.render({"contact_entries": entries})
            )
            entries.update(sent=True)

about/views.py
from django.views.generic import TemplateView


class Landing(TemplateView):

    template_name = "about/landing.html"

blog/views.py
from django.shortcuts import render

# Create your views here.

contact/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView

from contact.models import ContactEntry


class ContactEntryCreate(CreateView):

    fields = ["name", "email", "message"]
    model = ContactEntry
    success_url = reverse_lazy("contact:contact_entry_success")


class ContactEntrySuccess(TemplateView):

    template_name = "contact/contactentry_success.html"

home/views.py
from django.views.generic import TemplateView


class Landing(TemplateView):

    template_name = "home/landing.html"

it_assist/views.py
from django.views.generic import TemplateView


class Landing(TemplateView):

    template_name = "it_assist/landing.html"

about/templates/about/_nav.html
{% include "_nav_item.html" with link="experience" title="Experience" %}
{% include "_nav_item.html" with link="education" title="Education" %}
{% include "_nav_item.html" with link="skills" title="Skills" %}
{% include "_nav_item.html" with link="certs" title="Certificates" %}
{% include "_nav_item.html" with link="projects" title="Projects" %}

about/templates/about/base.html
{% extends "base.html" %}

{% block app_nav %}
    {% include "about/_nav.html" %}
{% endblock app_nav %}

blog/templates/blog/_back_nav.html
{% if request.GET.last %}
    <li class="nav-item">
        <a class="nav-link js-scroll-trigger" href="#" onclick="goBack()">Back</a>
    </li>
{% endif %}

blog/templates/blog/_nav.html
{% include "_nav_item.html" with link="posts" title="Posts" %}
{% if request.GET.tag %}
    <li class="nav-item">
        <a class="nav-link js-scroll-trigger" href="{% url 'wagtail_serve' '' %}?intro=false">All Posts</a>
    </li>
{% endif %}
{% include "_nav_item.html" with link="tags" title="Tags" %}

blog/templates/blog/_tags.html
{% for tag in tags %}
    <a href="{% url 'wagtail_serve' '' %}?tag={{ tag }}&amp;intro=false">
        <button type="button" class="btn btn-secondary mt-2 ml-1">{{ tag }}</button>
    </a>
{% endfor %}

blog/templates/blog/base.html
{% extends "base.html" %}

{% block app_nav %}
    {% include "blog/_nav.html" %}
{% endblock app_nav %}

{% block page_js %}
    <script type="text/javascript">
        function goBack() {
            window.history.back();
        }
    </script>
{% endblock page_js %}

blog/templates/blog/index.html
{% extends "blog/base.html" %}
{% load wagtailcore_tags blog_tags %}

{% block title %}
    {{ page.title }}
{% endblock title %}

{% block body %}
    <div class="container-fluid p-0">
        {% if request.GET.intro != "false" %}
            <section class="template-section" id="intro">
                <div class="template-section-content">
                    <h1 class="mb-0">{{ page.title|text_primary }}</h1>
                    {% if page.sub_title %}
                        <div class="subheading mb-5">
                            {{ page.sub_title }}
                        </div>
                    {% endif %}
                    {% if page.description %}
                        <p class="lead mb-5">{{ page.description }}</p>
                    {% endif %}
                </div>
            </section>
        {% endif %}

        <section class="template-section" id="posts">
            <div class="template-section-content">
                {% if request.GET.tag %}
                    <div class="subheading">
                        {{ request.GET.tag }} Tagged
                    </div>
                {% endif %}
                <h2 class="mb-5">Posts</h2>
                {% for post in posts %}
                    <div class="d-flex flex-column flex-md-row justify-content-between mb-5">
                        <div class="flex-grow-1">
                            <h3 class="mb-0"><a href="{% pageurl post %}?last=true">{{ post.title }}</a></h3>
                            <p>{{ post.specific.intro }}</p>
                        </div>
                        <div class="flex-shrink-0">
                            <span class="text-primary">{{ post.specific.date }}</span>
                        </div>
                    </div>
                {% endfor %}

            {# Only show pagination if there is more than one page to click through #}
                {% if posts.paginator.num_pages > 1 %}
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="pagination">
                                    {% if posts.has_previous %}
                                        <li class="page-item">
                                            <a href="{% pagination_path posts.previous_page_number %}" class="page-link">
                                                <span>&laquo;</span>
                                            </a>
                                        </li>
                                    {% endif %}

                                    {% for page_num in posts.paginator.page_range %}
                                        <li class="page-item {% if page_num == posts.number %} active{% endif %}">
                                            <a href="{% pagination_path page_num %}" class="page-link">
                                                {{ page_num }}
                                            </a>
                                        </li>
                                    {% endfor %}

                                    {% if posts.has_next %}
                                        <li class="page-item">
                                            <a href="{% pagination_path posts.next_page_number %}" class="page-link">
                                                <span>&raquo;</span>
                                            </a>
                                        </li>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
        </section>

        <section class="template-section" id="tags">
            <div class="template-section-content">
                <h2 class="mb-5">Tags</h2>
                {% include "blog/_tags.html" %}
            </div>
        </section>
    </div>
{% endblock body %}

blog/templates/blog/post.html
{% extends "blog/base.html" %}
{% load wagtailcore_tags wagtailimages_tags blog_tags %}

{% block app_nav %}
    <li class="nav-item">
        <a class="nav-link js-scroll-trigger" href="{% url 'wagtail_serve' '' %}">Blog</a>
    </li>
    {% include "_nav_item.html" with link="content" title="Content" %}
    {% if request.GET.last %}
        <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#" onclick="goBack()">Back</a>
        </li>
    {% endif %}
{% endblock app_nav %}

{% block title %}
    {{ page.title }}
{% endblock title %}

{% block body %}
    <div class="container-fluid p-0">
        <section class="template-section" id="intro">
            <div class="template-section-content">
                <h1 class="mb-0">{{ page.title|text_primary }}</h1>
                <div class="subheading mb-5">
                    {{ page.date }}
                </div>
                <p class="lead mb-5">{{ page.intro }}</p>
                {% if page.get_tags.exists %}
                    <div class="tags">
                        <h3>Tags</h3>
                        {% include "blog/_tags.html" with tags=page.get_tags %}
                    </div>
                {% endif %}
            </div>
        </section>

        <section class="template-section" id="content">
            <div class="template-section-content">
                {% for block in page.body %}
                    {% if block.block_type == "heading" %}
                        <div class="block-heading mt-5 mb-1">
                            <h2>{{ block.value }}</h2>
                        </div>
                    {% elif block.block_type == "image" %}
                        <div class="block-image my-5">
                            {% image block.value max-1104x1063 format-webp-lossless class="img-fluid" %}
                        </div>
                    {% elif block.block_type == "code" %}
                        <div class="block-code mb-5">
                            {% include_block block %}
                        </div>
                    {% else %}
                        <div class="block-{{ block.block_type }} my-3">
                            {% include_block block %}
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        </section>
    </div>
{% endblock body %}

contact/templates/contact/base.html
{% extends "base.html" %}

contact/templates/contact/contactentry_form.html
{% extends "contact/base.html" %}
{% load bootstrap %}

{% block title %}
    Contact Me
{% endblock title %}

{% block body %}
    <div class="container-fluid p-0">

        <section class="template-section" id="about">
            <div class="w-100">
                <h1 class="mb-0">Contact
                    <span class="text-primary">Me</span>
                </h1>
                <p class="lead mb-5">
                    <form role="form" method="POST">
                        {% csrf_token %}
                        {{ form|bootstrap }}
                        <div class="form-group">
                            <button type="submit" class="btn btn-secondary">Submit</button>
                        </div>
                    </form>
                </p>
            </div>
        </section>

    </div>
{% endblock body %}

contact/templates/contact/contactentry_success.html
{% extends "contact/base.html" %}
{% load bootstrap %}

{% block title %}
    Contact Me
{% endblock title %}

{% block body %}
    <div class="container-fluid p-0">

        <section class="template-section" id="about">
            <div class="w-100">
                <h1 class="mb-0">Contact
                    <span class="text-primary">Me</span>
                </h1>
                <p class="lead mb-5">
                    Sent! Thank you for reaching out. I will be in touch soon.
                </p>
            </div>
        </section>

    </div>
{% endblock body %}

home/templates/home/_nav.html
<li class="nav-item">
    <a class="nav-link js-scroll-trigger" href="{% url 'contact:contact_entry_create' %}">Contact</a>
</li>

home/templates/home/base.html
{% extends "base.html" %}

{% block app_nav %}
    {% include "home/_nav.html" %}
{% endblock app_nav %}

home/templates/home/landing.html
{% extends "home/base.html" %}

{% block title %}
    Welcome!
{% endblock title %}

{% block body %}
    <div class="container-fluid p-0">

        <section class="template-section" id="about">
            <div class="template-section-content">
                <h1 class="mb-0">Trevor
                    <span class="text-primary">Watson</span>
                </h1>
                <div class="subheading mb-5">Daytona Beach, FL ·
                    <a href="{% url 'contact:contact_entry_create' %}">Contact Me</a>
                </div>
                <p class="lead mb-5">An experienced programmer with a love for <a href="https://www.python.org/" target="_blank">python</a> and web development with <a href="https://www.djangoproject.com/" target="_blank">django</a>.</p>
                <div class="social-icons">
                    <a class="social-icon" href="https://www.linkedin.com/in/watsontrevor/" target="_blank">
                        <i class="fab fa-linkedin-in"></i>
                    </a>
                    <a class="social-icon" href="https://github.com/cfc603" target="_blank">
                        <i class="fab fa-github"></i>
                    </a>
                </div>
            </div>
        </section>

    </div>
{% endblock body %}

it_assist/templates/it_assist/_nav.html
{% include "_nav_item.html" with link="computers" title="Computers" %}
{% include "_nav_item.html" with link="telephone" title="telephone" %}
{% include "_nav_item.html" with link="development" title="Development" %}

it_assist/templates/it_assist/base.html
{% extends "base.html" %}

{% block app_nav %}
    {% include "it_assist/_nav.html" %}
{% endblock app_nav %}

it_assist/templates/it_assist/landing.html
{% extends "it_assist/base.html" %}
{% load static %}

{% block title %}
    IT Assistance
{% endblock title %}

{% block body %}
    <div class="container-fluid p-0">
        <section class="template-section" id="intro">
            <div class="template-section-content">
                <h1 class="mb-0">IT
                    <span class="text-primary">Services</span>
                </h1>
                <div class="subheading mb-5">Serving Volusia and Flagler ·
                    <a href="{% url 'contact:contact_entry_create' %}">Contact Me</a>
                </div>
                <p class="lead mb-5">Friendly, competent IT services.</p>

            </div>
        </section>

        <hr class="m-0">

        <section class="template-section" id="computers">
            <div class="template-section-content">
                <h2 class="mb-5">Computers</h2>

                <div class="d-flex flex-column flex-md-row justify-content-between mb-5" id="hd-upgrade">
                    <div class="flex-grow-1">
                        <h3 class="mb-0">Hard Drive Upgrade</h3>
                        <p>While many computers introduced in the past few years have included the newer, faster type of hard drive called SSD, most continue to use the old type, HDD. For a deep dive on the difference between the two, check out this article from <a href="https://www.intel.com/content/www/us/en/products/docs/memory-storage/solid-state-drives/ssd-vs-hdd.html" target="_blank">intel.com</a> The biggest takeaway is speed, 10 to 20 times of the older style.</p>
                        <p>If you are looking for a quick, cost effective way, upgrading your hard drive should definitely be considered.</p>
                    </div>
                </div>

                <div class="d-flex flex-column flex-md-row justify-content-between mb-5" id="backup">
                    <div class="flex-grow-1">
                        <h3 class="mb-0">Backup Install and Setup</h3>
                        <p>Hard Drives are, generally speaking, a very robust, dependable part of your computer, but they do fail. I don't know about you, but my day to day work life depends on accessing the data on my laptop. If the data were to disappear, it would be catastrophic.</p>
                        <p>The best way to mitigate risk, is have some insurance! In this case, a local backup and cloud backup.</p>
                    </div>
                </div>

                <div class="d-flex flex-column flex-md-row justify-content-between mb-5" id="virus">
                    <div class="flex-grow-1">
                        <h3 class="mb-0">Virus Removal</h3>
                        <p>Whoops! Did you accidentally download a virus? Don't despair. In many cases this can be quickly rectified.</p>
                    </div>
                </div>

                <div class="d-flex flex-column flex-md-row justify-content-between mb-5" id="antivirus">
                    <div class="flex-grow-1">
                        <h3 class="mb-0">Antivirus Setup</h3>
                        <p>While educating users is important in preventing virus's to start, an antivirus is going to provide that extra security. Let's face it, the people who create viruses are clever folks, and are always devising new ways trick PC users into downloading their programs.</p>
                        <p>Don't go unprotected, be sure to have antivirus software on all your computers.</p>
                    </div>
                </div>

                <div class="d-flex flex-column flex-md-row justify-content-between mb-5" id="wifi">
                    <div class="flex-grow-1">
                        <h3 class="mb-0">WiFi Setup</h3>
                        <p>Wifi is essential in a business these days, not only for your own computers, your customers will appreciate the faster connection while waiting. If not implemented correctly, you can leave your network open to vulnerabilities, or experience bad connections.</p>
                    </div>
                </div>

            </div>
        </section>

        <hr class="m-0">

        <section class="template-section" id="telephone">
            <div class="template-section-content">
                <h2 class="mb-5">Telephone</h2>

                <div class="d-flex flex-column flex-md-row justify-content-between mb-5" id="virtual-numbers">
                    <div class="flex-grow-1">
                        <h3 class="mb-0">Virtual Phone Numbers</h3>
                        <p>I LOVE virtual phone numbers, and I'm not sure why more businesses have not caught on to this. Here's the biggest use case, tracking advertisements.</p>
                        <p>My wife started her own lawn service on the side, she loves working outdoors. When she first started out, she tried a number of different advertising venues. Ironically, the cheapest advertising source gave her the largest ROI. In fact, something like 60% of her monthly revenue came from a $82 advertisement. At a fraction of her advertising budget, we were able to track this by having a virtual phone number for each advertising source.</p>
                    </div>
                </div>

                <div class="d-flex flex-column flex-md-row justify-content-between mb-5" id="ivr">
                    <div class="flex-grow-1">
                        <h3 class="mb-0">IVR Setup</h3>
                        <p>What is an IVR? Interactive Voice Response! Think about calling your Internet provider, "Press 1 for customer service; Press 2 for billing...", but way better. To name a few features:</p>
                        <p>
                            <ul>
                                <li>Voice Recognition</li>
                                <li>Accept Payments</li>
                                <li>Collect and Remit data</li>
                                <li>Add calls to a queue</li>
                            </ul>
                        </p>
                    </div>
                </div>

                <div class="d-flex flex-column flex-md-row justify-content-between mb-5" id="chatbots">
                    <div class="flex-grow-1">
                        <h3 class="mb-0">SMS Chatbots</h3>
                        <p>Text messaging is the primary source of communication in todays society. Unfortunately businesses have been slow to adopt in their tools of communicating with their customers. One of the reasons for this is having enough staff to promptly reply to customer messages.</p>
                        <p>A chatbot can be a great way to offer messaging without the additional staffing overhead. By programming the chatbot bot to answer frequent scenarios, and even collect and remit data, you can reduce the load on your employees, while offering a convenient way for your customers to engage with your company.</p>
                    </div>
                </div>

                <div class="d-flex flex-column flex-md-row justify-content-between mb-5" id="sms-appointments">
                    <div class="flex-grow-1">
                        <h3 class="mb-0">SMS Appointment Reminders</h3>
                        <p>I love my dentist office, not only because of the great work they do on keeping my smile healthy, but they send me a text reminding me of upcoming appointments. Thank you <a href="https://www.tomokafamilydentistry.com/" target="_blank">Tomoka Family Dentistry</a> for having this feature!</p>
                        <p>While a lot of <abbr title="Customer Relationship Manager">CRM's</abbr> are integrating text messaging into their software, not all on are on-board just yet. That's okay, we can certainly work around it.</p>
                    </div>
                </div>

            </div>
        </section>

        <hr class="m-0">

        <section class="template-section" id="development">
            <div class="template-section-content">
                <h2 class="mb-5">Development</h2>

                <div class="d-flex flex-column flex-md-row justify-content-between mb-5" id="web">
                    <div class="flex-grow-1">
                        <h3 class="mb-0">Websites</h3>
                        <p>While I'm not very proficient with the design side of websites, I know some very talented web designers that are. Once you have your site designed, you will need a back-end to make it all work, that's where I come in.</p>
                        <p>Whether you need basic hosting, or custom programing, let's <a href="{% url 'contact:contact_entry_create' %}">talk more</a>.</p>
                    </div>
                </div>

                <div class="d-flex flex-column flex-md-row justify-content-between mb-5" id="automation">
                    <div class="flex-grow-1">
                    <h3 class="mb-0">Repetition Automation</h3>
                    <p>If you perform a task on a computer over and over on your computer, you can probably automate it, freeing up your time for more thought provoking work.</p>
                    <p>Want to know if it can be automated, <a href="{% url 'contact:contact_entry_create' %}">lets talk</a>.</p>
                    </div>
                </div>

            </div>
        </section>
    </div>
{% endblock body %}

trevor_watson/templates/_nav_item.html
<li class="nav-item">
    <a class="nav-link js-scroll-trigger" href="#{{ link }}">{{ title }}</a>
</li>

trevor_watson/templates/base.html
{% load static google_analytics %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock title %} - Trevor Watson</title>

    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>

    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet" type="text/css" />

    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static "css/styles.css" %}" rel="stylesheet" />

    {# page level css #}
    {% block page_css %}
    {% endblock page_css %}

    {% google_analytics %}
</head>

<body id="page-top">

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="sideNav">
        <a class="navbar-brand js-scroll-trigger" href="{% url 'home:landing' %}#page-top">
            <span class="d-block d-lg-none">Trevor Watson</span>
            <span class="d-none d-lg-block">
                <img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="{% static "home/img/profile_20201016.jpg" %}" alt="">
            </span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="{% url 'home:landing' %}">Home</a>
                </li>
                {% block app_nav %}
                {% endblock app_nav %}
            </ul>
        </div>
    </nav>

    {% block body %}
    {% endblock body %}

    <!-- Bootstrap core JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>

    <!-- Third party plugin JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>

    <!-- Core theme JS-->
    <script src="{% static "js/scripts.js" %}"></script>

    {% block page_js %}
    {% endblock page_js %}

</body>

</html>